python -u train2.py \
       --display_name REGT_ORE2 \
        --dataset docred \
        --transformer_type roberta \
        --model_name_or_path ../PLM/roberta-large \
        --train_file train_annotated.json \
        --dev_file dev.json \
        --test_file test.json \
        --save_path ../trained_model/model_ORE2.pth \
        --num_train_epochs 40.0 \
        --train_batch_size 4 \
        --test_batch_size 4 \
        --seed 66 \
        --num_class 97 \
        --tau 0.2 \
        --gpu 1 \
        --learning_rate 1e-5\
        --loss SPU \